server:
  port: 8085
  servlet:
    context-path: /App
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbname
    username: root
    password: Pr@veen4795
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
rto:
    messages:
      ownerSaveScc :  your Registration is sucessfullly Your Registration ID = 
      ownerSaveFail : your Registration is Fail
  