server:
  port: 8085
  servlet:
    context-path: /App
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/formdb
    username: root
    password: Pr@veen4795
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    
    